apiVersion: v1
kind: Service
metadata:
  name: termind-service
spec:
  type: NodePort # Exposes the service outside the virtual cluster
  selector:
    app: termind
  ports:
    - protocol: TCP
      port: 80 # The port the Service listens on
      targetPort: 8000 # The port your Docker container is running on
